CREATE TYPE tipe_gajian_enum AS ENUM ('mingguan', 'dwimingguan', 'bulanan');

CREATE TABLE public.jadwal_gajian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    karyawan_id BIGINT NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    tipe_gajian tipe_gajian_enum NOT NULL,
    hari_tanggal_gajian JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.jadwal_gajian ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.jadwal_gajian
FOR SELECT USING (true);

CREATE POLICY "Allow authenticated insert" ON public.jadwal_gajian
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update" ON public.jadwal_gajian
FOR UPDATE USING (auth.role() = 'authenticated');
